import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin-ext"],
  weights: [400, 500, 600, 700],
  display: "swap",
  variable: "font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased text-zinc-100 bg-zinc-900`}>
        {children}
      </body>
    </html>
  );
}
